version: '3.9'
services:
  openweatherapi: 
    build: 
      #$LAT and $LON are referencing the shell environment LAT and LON variables
      #and passing it to the Dockerfile LAT, LONG
      #the syntax below ensures that the LAT, LONG arg will default to 
      #production if empty.
      #note that is dockerfile: is not specified it assumes file name: Dockerfile
      context: .
      args:
        - LAT=${LAT:-production}
        - LONG=${LONG:-production}
    environment: 
      - LAT=${LAT:-production}
      - LONG=${LONG:-production}
